"""empty message

Revision ID: 33c90b95b0b8
Revises: 609e9eb2257a
Create Date: 2025-09-14 12:54:29.763469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c90b95b0b8'
down_revision = '609e9eb2257a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_column('population')

    with op.batch_alter_table('development', schema=None) as batch_op:
        batch_op.add_column(sa.Column('development_class', sa.String(length=150), nullable=False))
        batch_op.drop_column('developmentClass')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('development', schema=None) as batch_op:
        batch_op.add_column(sa.Column('developmentClass', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('development_class')

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
