"""empty message

Revision ID: 7890e0371006
Revises: 33c90b95b0b8
Create Date: 2025-09-14 14:02:16.358651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7890e0371006'
down_revision = '33c90b95b0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('development', schema=None) as batch_op:
        batch_op.alter_column('development_class',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('index',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('development', schema=None) as batch_op:
        batch_op.alter_column('index',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('development_class',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
